apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
data:
  credentials: FwoGZXIvYXdzEKX//////////wEaDMNGOeg26E1MvdxUwiLVAc/OMfd9rAjqvWLFiWOIe/tpw8Gk0nODIBD6z5bd7vkvy/CBNQDesQ4Vbj1gTl9k1AC14iANP3fFVI3F4lNfOnOsdDM8yRSVo5c+9X2Z74cYutqOqGuSxrRhgUpqq2YM9hCa5oR6X9j5e1qvok3UMzcZfObW/4NX9hXws3ETcTgrttXUWrAe73N5ZUxG6RLjid6b5/DWMLeh+yKpVosjHU/HMXJidX/EdSQhd62s+usaXaLjTSFCgHPxiokfj/neefttYpawhsjcmUUVt7iMStrShKhdvCj//7amBjItw3/y/opfwzAFEnCMjLKOG/VyZpWiertMdsnPDajmzxLr8jgOrXRBXG2o90JM
type: Opaque
